// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw2ncej5WtApavq339GobKnJ8DA1sQKPs',
    appId: '1:202212390244:android:0c3f7d07f917c51c713671',
    messagingSenderId: '202212390244',
    projectId: 'expense-xpress',
    storageBucket: 'expense-xpress.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXrSQqzRKJW2My3-UK9qRzW20bQZuwGwc',
    appId: '1:202212390244:ios:1a3f7b2a99848e80713671',
    messagingSenderId: '202212390244',
    projectId: 'expense-xpress',
    storageBucket: 'expense-xpress.appspot.com',
    androidClientId: '202212390244-rlgo0ojb4nhf392n2ja3nke4r8bq0rmc.apps.googleusercontent.com',
    iosClientId: '202212390244-95hqsu127lohtl65593374d5f4vbhriq.apps.googleusercontent.com',
    iosBundleId: 'com.alfiee.expenseXpress',
  );
}
